import type { AIProvider } from '../ai/copilot-provider.js';
import type { Task } from '@matanelcohen/openspace-shared';

interface InnovationConfig {
  aiProvider: AIProvider;
  tasksDir: string;
  squadDir: string;
  intervalMs?: number; // default: 5 minutes
}

interface InnovationSuggestion {
  title: string;
  description: string;
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  category: 'bug' | 'performance' | 'security' | 'ux' | 'refactor' | 'feature';
}

export class InnovationService {
  private enabled = false;
  private timer: NodeJS.Timeout | null = null;
  private lastScan: string | null = null;
  private suggestionsCreated = 0;

  constructor(private config: InnovationConfig) {}

  async start(): Promise<void> {
    if (this.enabled) return;
    this.enabled = true;
    console.log('[Innovation] Mode started — lead will analyze and suggest improvements');
    await this.scan();
    this.timer = setInterval(() => this.scan(), this.config.intervalMs ?? 5 * 60 * 1000);
  }

  stop(): void {
    this.enabled = false;
    if (this.timer) { clearInterval(this.timer); this.timer = null; }
    console.log('[Innovation] Mode stopped');
  }

  getStatus() {
    return {
      enabled: this.enabled,
      lastScan: this.lastScan,
      suggestionsCreated: this.suggestionsCreated,
    };
  }

  async scan(): Promise<InnovationSuggestion[]> {
    this.lastScan = new Date().toISOString();
    console.log('[Innovation] Scanning codebase for improvement opportunities...');

    // Read project structure for context
    const { execSync } = await import('node:child_process');
    const projectDir = this.config.squadDir.replace(/\/.squad$/, '');

    let projectStructure = '';
    try {
      projectStructure = execSync('find apps packages -name "*.ts" -o -name "*.tsx" | head -50', {
        cwd: projectDir, encoding: 'utf-8', timeout: 10_000
      }).trim();
    } catch { /* ignore */ }

    let recentCommits = '';
    try {
      recentCommits = execSync('git log --oneline -10', {
        cwd: projectDir, encoding: 'utf-8', timeout: 10_000
      }).trim();
    } catch { /* ignore */ }

    // Read existing tasks to avoid duplicates
    const { readdir, readFile } = await import('node:fs/promises');
    let existingTitles: string[] = [];
    try {
      const files = await readdir(this.config.tasksDir);
      for (const f of files) {
        if (!f.endsWith('.md')) continue;
        try {
          const content = await readFile(`${this.config.tasksDir}/${f}`, 'utf-8');
          const titleMatch = content.match(/^title:\s*(.+)$/m);
          if (titleMatch) existingTitles.push(titleMatch[1].trim().toLowerCase());
        } catch { /* skip */ }
      }
    } catch { /* ignore */ }

    const result = await this.config.aiProvider.chatCompletion({
      systemPrompt:
        'You are Leela, the Lead of an AI engineering squad. ' +
        'Analyze the project and suggest 2-3 high-impact improvements. ' +
        'Focus on: bugs, performance bottlenecks, security issues, UX improvements, code quality. ' +
        'Only suggest actionable tasks with clear scope. ' +
        'Return ONLY a JSON array: [{"title":"...","description":"...","priority":"P1","category":"refactor"}]',
      messages: [{
        role: 'user',
        content: `Analyze this project and suggest improvements:\n\n` +
          `**Project files:**\n${projectStructure}\n\n` +
          `**Recent commits:**\n${recentCommits}\n\n` +
          `**Existing tasks (avoid duplicates):**\n${existingTitles.slice(0, 20).join(', ')}\n\n` +
          `Suggest 2-3 NEW improvements not already covered by existing tasks.`,
      }],
    });

    let suggestions: InnovationSuggestion[] = [];
    try {
      const match = result.content.match(/\[[\s\S]*\]/);
      if (match) suggestions = JSON.parse(match[0]);
    } catch {
      console.warn('[Innovation] Failed to parse suggestions');
      return [];
    }

    // Filter duplicates
    suggestions = suggestions.filter(s =>
      !existingTitles.includes(s.title.toLowerCase())
    );

    // Create tasks via API
    for (const s of suggestions) {
      try {
        const res = await fetch(`http://localhost:${process.env.PORT ?? 3001}/api/tasks`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: s.title,
            description: `${s.description}\n\n_Auto-generated by Innovation Mode (${s.category})_`,
            priority: s.priority,
            labels: ['innovation', s.category],
          }),
        });
        if (res.ok) {
          this.suggestionsCreated++;
          console.log(`[Innovation] Created task: ${s.title} (${s.priority}, ${s.category})`);
        }
      } catch (err) {
        console.warn(`[Innovation] Failed to create task: ${s.title}`, err);
      }
    }

    console.log(`[Innovation] Scan complete — ${suggestions.length} suggestions`);
    return suggestions;
  }
}
