/**
 * @matanelcohen/openspace-shared — Shared types, constants, and utilities.
 *
 * This package is the contract between frontend and backend.
 * Types defined here are the source of truth for both apps.
 */

// ── Types ──────────────────────────────────────────────────────────
export type {
  A2AArtifact,
  A2AConflictResolution,
  A2AConflictResolutionStrategy,
  A2ADelegationOutcome,
  A2ADelegationRequest,
  A2ADelegationRequestPayload,
  A2ADelegationResponse,
  A2ADelegationResponsePayload,
  A2AHandoff,
  A2AHandoffPayload,
  A2AHandoffReason,
  A2ALifecycleEvent,
  A2AMessage,
  A2AMessageEnvelope,
  A2AMessagePriority,
  A2AMessageStatus,
  A2AMessageType,
  A2ANegotiation,
  A2ANegotiationPayload,
  A2ANegotiationPhase,
  A2APayloadMap,
  A2AProgressStatus,
  A2ARetryPolicy,
  A2ARouter,
  A2ARoutingInfo,
  A2ARoutingStrategy,
  A2AStatusUpdate,
  A2AStatusUpdatePayload,
  ActivityEvent,
  ActivityEventType,
  Agent,
  AgentBoundaries,
  AgentDetail,
  AgentIdentity,
  AgentStatus,
  AttemptRecord,
  Channel,
  ChatChannel,
  ChatMessage,
  CheckpointMetadata,
  CheckpointStore,
  Chunk,
  ChunkFilter,
  ChunkingConfig,
  ChunkMetadata,
  ComparisonPredicate,
  ConditionalPredicate,
  ConditionNodeConfig,
  ConfidenceThreshold,
  DAGEdge,
  DAGNode,
  DAGWorkflow,
  DAGWorkflowEngineConfig,
  Decision,
  DecisionStatus,
  Edge,
  EmbeddedChunk,
  Embedder,
  EmbeddingConfig,
  EmbeddingProvider,
  EnhancedNodeExecutionState,
  EnhancedNodeExecutionStatus,
  EnhancedWorkflowExecutionState,
  EnhancedWorkflowExecutionStatus,
  AuditEntry,
  EscalationChain,
  EscalationItem,
  EscalationPriority,
  EscalationResolution,
  EscalationStatus,
  ExecutionContext,
  ExpressionPredicate,
  ExtractedMemory,
  GitHubIssue,
  GitHubPR,
  HITLGateNodeConfig,
  IngestionState,
  LogicalPredicate,
  ManifestVersion,
  Memory,
  MemoryAttribution,
  MemoryConfig,
  MemoryConsolidationResult,
  MemoryCreateInput,
  MemoryExtractionInput,
  MemoryRecallResult,
  MemorySearchRequest,
  MemorySearchResponse,
  MemorySearchResult,
  MemorySettings,
  MemoryStoreStats,
  MemoryType,
  MemoryUpdateInput,
  MemoryWithMeta,
  NodeExecutionState,
  NodeExecutionStatus,
  NodeHandler,
  NodeOutput,
  ParallelJoinNodeConfig,
  ParameterMapping,
  PromptRole,
  PromptVariable,
  RAGConfig,
  RAGSearchRequest,
  RAGSearchResponse,
  RAGService,
  RAGStats,
  RetrievalConfig,
  RetrievalContext,
  RetrievedChunk,
  ExecRequest,
  ExecResult,
  SandboxCreateInput,
  SandboxFile,
  SandboxInfo,
  SandboxResourceLimits,
  SandboxRuntime,
  SandboxStatus,
  StreamChunk,
  StreamEnd,
  SemVer,
  SerializedContext,
  SkillCircuitBreakerState,
  SkillConfigSchema,
  SkillContext,
  SkillDependency,
  SkillHealthStatus,
  SkillLifecycleHooks,
  SkillManifest,
  SkillMatchResult,
  SkillPermission,
  SkillPhase,
  SkillPromptTemplate,
  SkillRegistry,
  SkillRegistryEntry,
  SkillRetryPolicy,
  SkillToolDeclaration,
  SkillTrigger,
  SkillValidationResult,
  SourceAttribution,
  SourceType,
  SquadConfig,
  SquadOverview,
  StepNode,
  StepNodeConfig,
  StepNodeType,
  SubWorkflowNodeConfig,
  Task,
  TaskAssigneeType,
  TaskCounts,
  TaskNodeConfig,
  TaskPriority,
  TaskStatus,
  TeamMember,
  TeamMemberRank,
  TeamMemberStatus,
  Tool,
  ToolCapabilityTag,
  ToolExecution,
  ToolExecutionStatus,
  ToolInputSchema,
  ToolParameter,
  ToolParameterType,
  ToolRegistryRef,
  ToolSuggestion,
  VectorSearchQuery,
  VectorSearchResult,
  VectorStore,
  VectorStoreConfig,
  VectorStoreProvider,
  VoiceMessage,
  VoiceParticipantRole,
  VoiceProfile,
  VoiceSession,
  VoiceSessionStatus,
  WorkflowDefinition,
  WorkflowEvent,
  WorkflowEventHandler,
  WorkflowEventPayload,
  WorkflowExecutionState,
  WorkflowExecutionStatus,
  WorkflowNodeType,
  WorkflowResolver,
  WorkflowStartOptions,
  Workspace,
} from './types/index.js';

// ── Escalation Engine ──────────────────────────────────────────────
export {
  approveEscalationItem,
  autoEscalate,
  calculateTimeout,
  claimEscalationItem,
  createEscalationItem,
  deserializeQueueState,
  evaluateConfidence,
  generateId,
  getNextChainLevel,
  isAtThresholdBoundary,
  isReviewerEligible,
  isTimedOut,
  rejectEscalationItem,
  remainingTimeMs,
  resolveChainLevel,
  serializeQueueState,
  validateContext,
} from './escalation/index.js';

// ── Workflow Engine ────────────────────────────────────────────────
export {
  collectNodeInputs,
  createExecutionState,
  deriveWorkflowStatus,
  deserializeExecutionState,
  getReadyNodes,
  hasCycle,
  serializeExecutionState,
  topologicalSort,
  updateNodeState,
  validateWorkflow,
  WorkflowEngine,
} from './workflow/index.js';

// ── Constants ──────────────────────────────────────────────────────
export type { AgentRole, Department } from './constants/index.js';
export {
  ACTIVITY_EVENT_TYPE_LABELS,
  ACTIVITY_EVENT_TYPES,
  AGENT_ROLES,
  AGENT_STATUS_LABELS,
  AGENT_STATUSES,
  CHAT_CHANNEL_PREFIX,
  CHAT_TEAM_RECIPIENT,
  DEPARTMENTS,
  TASK_PRIORITIES,
  TASK_PRIORITY_LABELS,
  TASK_STATUS_LABELS,
  TASK_STATUSES,
  TEAM_MEMBER_RANK_LABELS,
  TEAM_MEMBER_RANKS,
  TEAM_MEMBER_STATUS_LABELS,
  TEAM_MEMBER_STATUSES,
} from './constants/index.js';

// ── Skills ─────────────────────────────────────────────────────
export * from './types/skill.js';

// ── Squad SDK Config ──────────────────────────────────────────
export type {
  AgentCapability,
  AgentDefinition,
  CeremonyDefinition,
  HooksDefinition,
  ModelConfig,
  ResponseTier,
  RoutingDefinition,
  RoutingRule,
  SandboxDefinition,
  SquadSDKConfig,
  TeamDefinition,
  TelemetryDefinition,
} from './config/define.js';
export {
  defineAgent,
  defineCeremony,
  defineHooks,
  defineRouting,
  defineSandbox,
  defineSquad,
  defineTeam,
  defineTelemetry,
} from './config/define.js';
